### ISSUE TITLE
Bug: Server error on file upload

### ISSUE THREAD

**Issue by AatmikMallya** [ChatTutor/chattutor#121]
Dirk pointed out a bug in the main branch (https://chattutor-git-nbqjgewnea-uc.a.run.app/static/chattutor.html). Uploading this file returns a server error:
[cqn.txt](https://github.com/AxiomaticAI-Inc/chattutor/files/13233962/cqn.txt)

The issue is most likely in the `reader.py` file.

**Comment by berncasa** [comment]
that was mainly due to a not consistent handling of the files types in the upload_data_to_process
i tried to clean it a little bit and solved the problem
main changes:
- renamed functions and variables to add consistency
- decode bytes before parse_plaintext_file
- added a function to automatically detect the encoding, ie, utf8, ascii, etc

**Comment by berncasa** [comment]
@dmitrii-briantcev, I apologize I did not see that the task was assigned to you
